export const SAVE_PROVERB = "SAVE_PROVERB";
export const SAVE_PROVERB_FAIL = "SAVE_PROVERB_FAIL";
export const SAVE_PROVERB_SUCCESS = "SAVE_PROVERB_SUCCESS";
export const GET_LATEST_PROVERB = "GET_LATEST_PROVERB";
export const GET_LATEST_PROVERB_FAIL = "GET_LATEST_PROVERB_FAIL";
export const GET_LATEST_PROVERB_SUCCESS = "GET_LATEST_PROVERB_SUCCESS";
