export const SAVE_PROVERB = "SAVE_PROVERB";
export const SAVE_PROVERB_FAIL = "SAVE_PROVERB_FAIL";
export const SAVE_PROVERB_SUCCESS = "SAVE_PROVERB_SUCCESS";
export const GET_PROVERBS = "GET_PROVERBS";
export const GET_PROVERBS_FAIL = "GET_PROVERBS_FAIL";
export const GET_PROVERBS_SUCCESS = "GET_PROVERBS_SUCCESS";
